name: GCP Secret Manager
description: Read secrets from Google Cloud Secret Manager
author: https://github.com/avaly/gcp-secret-manager-buildkite-plugin
requirements: []
configuration:
  properties:
    pattern:
      type: string
  additionalProperties: false
